= Course overview
:page-toclevels: 2


// This content will only appear in the site.
ifndef::loader-assembler[]
.PDF version of the course
[NOTE]
====
*You need to access this content offline?* You can downlod the PDF version of the course {site-url}/{page-component-name}/{page-component-version}/_exports/{page-component-name}-{page-component-version}.pdf[here]
====
endif::[]

== 🎯 Course Objective

This course provides a practical and in-depth exploration of LabVIEW's Event-driven programming model.  
You'll learn how to build responsive, maintainable applications using {es}s, User Events, and best practices for scalable architectures.

== 👥 Target Audience

* Intermediate LabVIEW developers
* Engineers designing interactive UIs
* Developers transitioning from polling to event-driven architectures

== 🗂️ Course Outline

=== Introduction to Events

Understand the motivation behind LabVIEW's event-driven programming.  
Compare polling-based and event-based interaction strategies.

=== Event Sources

List all kind of sources for events an Event Structure

=== Event Types

Understand the differnece between filtered and non-filtered events.

=== Memory Management

Understand how LabVIEW handle the memory when it comes to deal with events. 

== ✅ Learning Outcomes

After completing this course, you will be able to:

* Use Event Structures to build responsive UIs
* Register and generate custom User Events
* Troubleshoot and avoid common design pitfalls
* Architect scalable LabVIEW applications using Events
